[versions]
kotlin = "2.1.0"
ktor = "3.1.2"
kotlinx-html = "0.12.0"
kotlinx-serialization = "1.6.2"
dungeon-hub-api = "0.5.7"
kord-extensions = "2.3.1-SNAPSHOT"
logback = "1.5.18"
dotenv = "6.5.1"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktor" }

kotlinx-html-jvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

dungeon-hub-api-client = { module = "net.dungeon-hub.api:client", version.ref = "dungeon-hub-api" }

dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
